stages:
  - build
  
group10image1:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build

  before_script:
    - echo $CI_PROJECT_DIR

  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/web --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE/group10image1:$CI_COMMIT_TAG

  only:
    - master

  tags:
    - daedalus

group10image2:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build

  before_script:
    - echo $CI_PROJECT_DIR

  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/client --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE/group10image2:$CI_COMMIT_TAG

  only:
    - master

  tags:
    - daedalus

