apiVersion: apps/v1
kind: Deployment
metadata:
  name: gropu10predictor-deployment
  labels:
    app: gropu10predictor
spec:
  selector:
    matchLabels:
      app: gropu10predictor
  replicas: 1
  template:
    metadata:
      labels:
        app: gropu10predictor
    spec:
      containers:
      - name: gropu10predictor
        image: "gitlab.ldv.ei.tum.de:5005/ami2021/group10/group10image:latest"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: k8s-group10-reg
